Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/unicorn/*.rb'

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

